"""alter identifier column to String(10), unique, not null

Revision ID: 3fc4bb5d174a
Revises: 5fbcdfca9dad
Create Date: 2025-12-16 18:55:35.905979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc4bb5d174a'
down_revision: Union[str, Sequence[str], None] = '5fbcdfca9dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'cattle',
        'identifier',
        existing_type=sa.VARCHAR(),
        type_=sa.String(10),
        nullable=False
    )

    op.create_unique_constraint(None, 'cattle', ['identifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cattle', type_='unique')
    op.alter_column('cattle', 'identifier',
           existing_type=sa.String(10),
           type_=sa.String(),  # back to unbounded
           nullable=True)
    # ### end Alembic commands ###
