"""create herds table

Revision ID: cd535cc75c40
Revises: 3fc4bb5d174a
Create Date: 2025-12-16 20:56:15.856433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd535cc75c40'
down_revision: Union[str, Sequence[str], None] = '3fc4bb5d174a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('herds',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('cattle', sa.Column('herd_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'cattle', 'herds', ['herd_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cattle', type_='foreignkey')
    op.drop_column('cattle', 'herd_id')
    op.drop_table('herds')
    # ### end Alembic commands ###
